name: Checkout Code

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify SSH connection
        run: ssh -T git@github.com

      - name: Perform Git operations
        run: |
          git clone https://github.com/mrudulasai/iib-ace.git
