name: Connect to Azure VM
 
on:
  push:
    branches:
      - main
 
jobs:
  connect-to-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up SSH
        run: |
          echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > /home/azureuser/.ssh/id_rsa
          chmod 600 /home/azureuser/.ssh/id_rsa
          echo "Host azure-vm" >> /home/azureuser/.ssh/config
          echo "  HostName ${{ secrets.AZURE_VM_IP }}" >> /home/azureuser/.ssh/config
          echo "  User azureuser" >> /home/azureuser/.ssh/config
          echo "  StrictHostKeyChecking no" >> /home/azureuser/.ssh/config
 
      - name: Connect and run commands on VM
        run: |
          ssh azure-vm "echo 'Connected successfully'; uname -a"
