name: Connect to Azure VM
 
on:
  push:
    branches:
      - main
 
jobs:
  connect-to-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host azure-vm" >> ~/.ssh/config
          echo "  HostName ${{ secrets.AZURE_VM_IP }}" >> ~/.ssh/config
          echo "  User your_username" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
 
      - name: Connect and run commands on VM
        run: |
          ssh azure-vm "echo 'Connected successfully'; uname -a"
