name: Backup IIB

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run IIB Backup Script
        run: |
          ssh -o StrictHostKeyChecking=no user@your-local-server 'bash -s' < .github/workflows/scripts/remote_backup.sh


      # - name: Run mqsiprofile command
      #   env:
      #     USERNAME: ${{ secrets.REMOTE_USER }}
      #     PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
      #   run: |
      #     echo "Running IIB commands..."
      #     . /opt/ibm/mqsi/iib-10.0.0.7/server/bin/mqsiprofile
