name: Connect to Azure VM

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test Azure VM
        run: |
          mkdir /etc/ansible/scripts/


